syn keyword cmakeStatement
	\ CHECK_INCLUDE_FILE CHECK_INCLUDE_FILE_CXX CHECK_TYPE_SIZE GET_PROPERTY QT4_WRAP_UI QT4_ADD_RESOURCES
  \ SET_PROPERTY CHECK_SYMBOL_EXISTS CHECK_LIBRARY_EXISTS CHECK_INCLUDE_FILES FLEX_TARGET FUNCTION
  \ ENDFUNCTION

syn keyword cmakeOperators
	\ DEPENDS

syn keyword cmakeSystemVariables
	\ UNIX
