syn keyword cmakeStatement
	\ FLEX_TARGET FUNCTION ENDFUNCTION RETURN 
  \ QT4_ADD_RESOURCES QT4_WRAP_UI QT4_WRAP_CPP
	\ CHECK_INCLUDE_FILE CHECK_INCLUDE_FILE_CXX CHECK_INCLUDE_FILES
	\ SET_PROPERTY GET_PROPERTY
	\ CHECK_TYPE_SIZE CHECK_SYMBOL_EXISTS CHECK_LIBRARY_EXISTS

syn keyword cmakeOperators
	\ DEPENDS

syn keyword cmakeSystemVariables
	\ UNIX
